name: sclens-py
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - cudatoolkit
  - nomkl
  - pandas
  - numpy
  - scipy
  - anndata
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - joblib
  - python-igraph
  - numba
  - resample
  - umap-learn  
  - pip

  - pip:
    - tqdm-joblib
    - umap-learn[plot] 

